### ISSUE TITLE
bug: "~": The system cannot find the file specified. (os error 2)

### ISSUE THREAD

**Issue by cyntheticfox** [cafkafk/eza#1095]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
- The command-line arguments you are using
- Your shell and terminal
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

- version: v0.19.0
- args: just `eza.exe ~`
- shell: Windows PowerShell v5.1.22621.3958, PowerShell 7.4.4
- Terminal: Windows Terminal 1.20.11781.0
- OS: Windows 11 Enterprise 22H2 x86_64

**Comment by jschpp** [comment]
That is a known problem with Powershell.
See the docs here: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-5.1&WT.mc_id=ps-gethelp#tilde-

Specifically this part:
```
When you use the tilde character with native commands, PowerShell passes the tilde as a literal character. Using the tilde in a path causes errors for native commands on Windows that don't support the tilde character.
```

As far as I know rust uses the windows API in the background which doesn't handle `~` as a special directory. The only way I'd see to resolve this in `eza` would be to handle `~` as special case on windows.

For the moment you can tab expand `~` in powershell which will then pass the full pass onwards to eza. If you want to use `~` in a script I'd call `eza` like this `eza $(Resolve-Path "~")` of like this `eza $env:HOME`

**Comment by ChrisDenton** [comment]
Yes, the Rust standard library just uses the Windows API and it's very unlikely this will ever change. `~` is after all a valid file name and the std can't second guess whether you meant the home directory or not.

**Comment by cafkafk** [comment]
I'm reading here that this isn't really an eza issue?

**Comment by jschpp** [comment]
@cafkafk you could in theory have `eza` expand `~` at the start of a path into the home directory under windows. But that would be a special case for Windows only.

In my opinion that should not be the job of `eza` though. :shrug:

**Comment by cafkafk** [comment]
> In my opinion that should not be the job of `eza` though. 🤷

I think you're right, it's gonna be too brittle, if anything, this should be fixed in the windows API or `std` I suppose.

**Comment by ChrisDenton** [comment]
On Linux `~` is interpreted by the shell not the Linux filesystem APIs nor Rust's std ([example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=10395d14b5361458931082b6da9fe313)).

On Windows, you would need to either persuade powershell to expand it for native commands or continue to do something like `eza (rvpa ~)` to resolve it to a full path. Alternatively you can use `$home` or set a shorter variable (like `$h`) in your profile script.

**Comment by oliverhr** [comment]
Alternatively to what @ChrisDenton suggested you can create an Alias:

```
function _eza {
    switch ($MyInvocation.InvocationName) {
        ls { eza -G }
    }
}
Set-Alias -Value _eza -Name ls
```
`eza -G` is the same as `eza` just wanted to be explicit.
