### ISSUE TITLE
EZA_COLORS with updates

### ISSUE THREAD

**Issue by muchgitsuchwow** [cafkafk/eza#572]
Hey guys,

since exa has been forked nearly any update "forced" me to update EZA_COLORS to remove files being colored by default. With the current version 

```
eza - A modern, maintained replacement for ls
v0.15.1 [+git]
https://github.com/eza-community/eza
```

it looks like that various programming language files are now yellow. Is there any simple way to disable this behaviour? I really doesn't like the idea of updating EZA_COLORS to something like `*.go=reset:*.rs=reset:*.lua=reset` et cetera.

This leads me to a suggestion: Features and updates like such are a great thing, but lately you force people to opt-out.

**Comment by MartinFillon** [comment]
According to the man of eza_colors explanation you could either overrides them manually by doing something such as: `EZA_COLORS="*.go=37"` which is the same as reset as it paints the text blank
