### ISSUE TITLE
About the -A flag

### ISSUE THREAD

**Issue by cafkafk** [cafkafk/eza#70]
Currently there are 3 PRs trying to implement an `-A` flag. I'm unsure which one is preferred to focus on.

https://github.com/cafkafk/eza/pulls?q=is%3Apr+is%3Aopen+label%3A%22-A+flag%22

@sbatial how do you feel about this?

**Comment by sbatial** [comment]
I'm definitely very much in favor of this feature.
I try to determine which one looks the best

**Comment by sbatial** [comment]
I'd say https://github.com/cafkafk/eza/pull/43 is my favorite.
I can't imagine the match/calculation is that computationally expensive to rule it out and it looks the most comprehensive if there aren't any bugs.

I will go over the match first because I'm sure than can be condensed a bit more

**Comment by cafkafk** [comment]
> I'd say #43 is my favorite.

I'm gonna close the other two for now then.

> I will go over the match first because I'm sure than can be condensed a bit more

Good luck!
